INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (1, 186, 64, '2008', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (2, 148, 64, 'Aachen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (3, 197, 64, 'Aalen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (4, 189, 64, 'Afrika', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (5, 0, 64, 'Aktuelle Berichte', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (6, 295, 64, 'Alb-Schwarzwald', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (7, 185, 64, 'Ammerland/Oldenburg-Stadt/Wesermarsch', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (8, 104, 64, 'Archive', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (9, 189, 128, 'Asien', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (10, 237, 64, 'Augsburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (11, 103, 64, 'Australien', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (12, 189, 192, 'Australien/Ozeanien', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (13, 0, 128, 'Baden', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (14, 178, 64, 'Bamberg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (15, 0, 192, 'Bayern', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (16, 178, 128, 'Bayreuth', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (17, 161, 64, 'Bergisch-Land', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (18, 95, 64, 'Bergstraße', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (19, 0, 256, 'Berlin', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (20, 36, 64, 'Bezirk Eisenstadt und Umgebung', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (21, 36, 128, 'Bezirk Güssing', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (22, 36, 192, 'Bezirk Jennersdorf', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (23, 36, 256, 'Bezirk Mattersburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (24, 36, 320, 'Bezirk Neusiedl am See', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (25, 36, 384, 'Bezirk Oberpullendorf', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (26, 36, 448, 'Bezirk Oberwart', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (27, 246, 64, 'Bibliotheken & Schach', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (28, 200, 64, 'Bielefeld', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (29, 224, 64, 'Bochum', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (30, 13, 64, 'Bodensee', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (31, 148, 128, 'Bonn', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (32, 154, 64, 'Borken', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (33, 0, 320, 'Brandenburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (34, 162, 64, 'Braunschweig', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (35, 0, 384, 'Bremen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (36, 184, 64, 'Burgenland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (37, 227, 64, 'Chemnitz', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (38, 246, 128, 'Chinesisches Schach', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (39, 178, 192, 'Coburg/Neustadt', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (40, 0, 448, 'Computer', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (41, 33, 64, 'Cottbus', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (42, 103, 128, 'Dänemark', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (43, 246, 192, 'Dame', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (44, 40, 64, 'Datenbanken', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (45, 228, 64, 'Dessau', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (46, 5, 64, 'Deutsche Jugendmeisterschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (47, 5, 128, 'Deutsche Meisterschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (48, 0, 512, 'Deutsche Seiten', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (49, 0, 576, 'Deutscher Schachbund', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (50, 66, 64, 'Deutschland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (51, 6, 64, 'Donau/Neckar', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (52, 224, 128, 'Dortmund', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (53, 227, 128, 'Dresden', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (54, 161, 128, 'Düsseldorf', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (55, 161, 192, 'Duisburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (56, 0, 640, 'DWZ und Rating', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (57, 46, 64, 'Einzel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (58, 47, 64, 'Einzel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (59, 0, 704, 'Email und Fernschach', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (60, 224, 192, 'Emscher-Lippe', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (61, 271, 64, 'Endspiele', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (62, 271, 128, 'Eröffnungen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (63, 224, 256, 'Essen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (64, 156, 64, 'Esslingen/Nürtingen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (65, 5, 192, 'EU-Meisterschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (66, 189, 256, 'Europa', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (67, 5, 256, 'Europacup für Vereinsmannschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (68, 5, 320, 'Europameisterschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (69, 189, 320, 'FIDE', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (70, 156, 128, 'Filstal', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (71, 104, 128, 'Fotos', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (72, 95, 128, 'Frankfurt/Main', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (73, 33, 128, 'Frankfurt/Oder', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (74, 103, 192, 'Frankreich', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (75, 286, 64, 'Frauen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (76, 13, 128, 'Freiburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (77, 246, 256, 'Go', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (78, 252, 64, 'Graz', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (79, 103, 256, 'Griechenland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (80, 103, 320, 'Großbritannien', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (81, 117, 64, 'Händler', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (82, 228, 128, 'Halle', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (83, 0, 768, 'Hamburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (84, 224, 320, 'Hamm', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (85, 162, 128, 'Hannover', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (86, 85, 64, 'Hannover-Land', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (87, 85, 128, 'Hannover-Stadt', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (88, 40, 128, 'Hardware', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (89, 276, 64, 'Haßberge-Rhön', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (90, 13, 192, 'Heidelberg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (91, 197, 128, 'Heidenheim', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (92, 277, 64, 'Heilbronn-Hohenlohe', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (93, 200, 128, 'Hellweg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (94, 224, 384, 'Herne', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (95, 0, 832, 'Hessen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (96, 246, 320, 'Historie', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (97, 13, 256, 'Hochrhein', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (98, 266, 64, 'Hochsauerland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (99, 178, 256, 'Hof', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (100, 160, 64, 'Industrieviertel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (101, 176, 64, 'Ingolstadt-Freising', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (102, 176, 128, 'Inn-Chiemgau', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (103, 0, 896, 'Internationale Seiten', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (104, 0, 960, 'Internet', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (105, 103, 384, 'Irland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (106, 266, 128, 'Iserlohn', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (107, 103, 448, 'Italien', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (108, 246, 384, 'Japanisches Schach', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (109, 68, 64, 'Jugend', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (110, 286, 128, 'Jugend', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (111, 184, 128, 'Kärnten', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (112, 201, 64, 'Kaiserslautern', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (113, 13, 320, 'Karlsruhe', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (114, 127, 64, 'Kataloge', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (115, 236, 64, 'Kiel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (116, 148, 192, 'Köln', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (117, 0, 1024, 'Kommerzielle Seiten', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (118, 286, 192, 'Ländermannschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (119, 68, 128, 'Ländermannschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (120, 46, 128, 'Ländermeisterschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (121, 95, 192, 'Lahn', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (122, 95, 256, 'Lahn/Eder', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (123, 201, 128, 'Landau', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (124, 227, 192, 'Leipzig', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (125, 178, 320, 'Lichtenfels/Kronach', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (126, 161, 256, 'Linker Niederrhein', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (127, 0, 1088, 'Linksammlungen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (128, 200, 192, 'Lippe', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (129, 277, 128, 'Ludwigsburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (130, 162, 192, 'Lüneburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (131, 103, 512, 'Luxemburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (132, 228, 192, 'Magdeburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (133, 95, 320, 'Main-Taunus', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (134, 95, 384, 'Main-Vogelsberg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (135, 276, 128, 'Maindreieck', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (136, 276, 192, 'Mainspessart', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (137, 13, 384, 'Mannheim', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (138, 178, 384, 'Marktredwitz', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (139, 0, 1152, 'Mecklenburg-Vorpommern', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (140, 146, 64, 'Mitte', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (141, 255, 64, 'Mitte', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (142, 139, 64, 'Mitte', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (143, 269, 64, 'Mitte', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (144, 179, 64, 'Mitte', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (145, 13, 448, 'Mittelbaden', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (146, 15, 64, 'Mittelfranken', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (147, 95, 448, 'Mittelrhein', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (148, 173, 64, 'Mittelrhein', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (149, 237, 128, 'Mittelschwaben', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (150, 160, 128, 'Mostviertel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (151, 224, 448, 'Mülheim', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (152, 15, 128, 'München', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (153, 154, 128, 'Münster', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (154, 173, 128, 'Münsterland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (155, 186, 128, 'Nachwuchs-Olympiaden', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (156, 295, 128, 'Neckar-Fils', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (157, 104, 192, 'Newsgroups', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (158, 15, 192, 'Niederbayern', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (159, 103, 576, 'Niederlande', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (160, 184, 192, 'Niederösterreich', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (161, 173, 192, 'Niederrhein', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (162, 0, 1216, 'Niedersachsen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (163, 85, 192, 'Nienburg-Schaumburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (164, 146, 128, 'Nord', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (165, 236, 128, 'Nord', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (166, 182, 64, 'Nord', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (167, 269, 128, 'Nord', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (168, 179, 128, 'Nord', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (169, 252, 128, 'Nord', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (170, 201, 192, 'Nord-Ost', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (171, 189, 384, 'Nordamerika', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (172, 95, 512, 'Nordhessen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (173, 0, 1280, 'Nordrhein-Westfalen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (174, 237, 192, 'Nordschwaben', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (175, 103, 640, 'Norwegen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (176, 15, 256, 'Oberbayern', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (177, 266, 192, 'Oberberg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (178, 15, 320, 'Oberfranken', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (179, 184, 256, 'Oberösterreich', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (180, 229, 64, 'Oberösterreich', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (181, 15, 384, 'Oberpfalz', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (182, 295, 192, 'Oberschwaben', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (183, 13, 512, 'Odenwald', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (184, 103, 704, 'Österreich', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (185, 162, 256, 'Oldenburg-Ostfriesland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (186, 5, 384, 'Olympiaden', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (187, 104, 256, 'Online-Datenbanken', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (188, 104, 320, 'Online-Schach', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (189, 0, 1344, 'Organisationen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (190, 13, 576, 'Ortenau', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (191, 162, 320, 'Osnabrück-Emsland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (192, 146, 192, 'Ost', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (193, 255, 128, 'Ost', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (194, 139, 128, 'Ost', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (195, 269, 192, 'Ost', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (196, 236, 192, 'Ost', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (197, 295, 256, 'Ostalb', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (198, 185, 128, 'Ostfriesland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (199, 95, 576, 'Osthessen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (200, 173, 256, 'Ostwestfalen-Lippe', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (201, 223, 64, 'Pfalz', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (202, 13, 640, 'Pforzheim', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (203, 201, 256, 'Pirmasens', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (204, 117, 128, 'Pokale & Ehrenpreise', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (205, 200, 256, 'Porta', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (206, 103, 768, 'Portugal', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (207, 33, 192, 'Potsdam', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (208, 0, 1408, 'Private Homepages', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (209, 271, 192, 'Probleme', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (210, 0, 1472, 'Problemschach & Studien', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (211, 201, 320, 'Ramstein', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (212, 229, 128, 'Region Flachgau', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (213, 229, 192, 'Region Pinzgau', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (214, 229, 256, 'Region Pongau', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (215, 229, 320, 'Region Tennengau', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (216, 156, 192, 'Reutlingen/Tübingen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (217, 222, 64, 'Rhein-Ahr-Mosel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (218, 222, 128, 'Rhein-Nahe', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (219, 222, 192, 'Rhein-Westerwald', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (220, 148, 256, 'Rhein-Wupper', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (221, 223, 128, 'Rheinhessen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (222, 223, 192, 'Rheinland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (223, 0, 1536, 'Rheinland-Pfalz', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (224, 173, 320, 'Ruhrgebiet', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (225, 148, 320, 'Rur-Erft', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (226, 0, 1600, 'Saarland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (227, 0, 1664, 'Sachsen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (228, 0, 1728, 'Sachsen-Anhalt', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (229, 184, 320, 'Salzburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (230, 246, 448, 'Sammler', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (231, 266, 256, 'Sauerland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (232, 246, 512, 'Schachmuseen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (233, 40, 192, 'Schachprogramme', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (234, 117, 192, 'Schachtourismus', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (235, 246, 576, 'Schachvariationen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (236, 0, 1792, 'Schleswig-Holstein', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (237, 15, 448, 'Schwaben', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (238, 197, 192, 'Schwäbisch Gmünd', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (239, 13, 704, 'Schwarzwald', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (240, 6, 128, 'Schwarzwald', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (241, 103, 832, 'Schweden', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (242, 103, 896, 'Schweiz', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (243, 286, 256, 'Senioren', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (244, 47, 128, 'Senioren', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (245, 266, 320, 'Siegerland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (246, 0, 1856, 'Sonstige Seiten', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (247, 103, 960, 'Spanien', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (248, 276, 256, 'Spessart-Untermain', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (249, 0, 1920, 'Spieler', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (250, 229, 384, 'Stadt Salzburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (251, 95, 640, 'Starkenburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (252, 184, 384, 'Steiermark', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (253, 154, 192, 'Steinfurt', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (254, 271, 256, 'Strategie', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (255, 295, 320, 'Stuttgart', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (256, 146, 256, 'Süd', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (257, 182, 128, 'Süd', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (258, 269, 256, 'Süd', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (259, 179, 192, 'Süd', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (260, 252, 192, 'Süd', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (261, 189, 448, 'Südamerika', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (262, 162, 384, 'Südniedersachsen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (263, 185, 192, 'Südoldenburg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (264, 237, 256, 'Südschwaben', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (265, 103, 1024, 'Südtirol', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (266, 173, 384, 'Südwestfalen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (267, 271, 320, 'Taktik', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (268, 200, 320, 'Teutoburger Wald-West', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (269, 0, 1984, 'Thüringen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (270, 184, 448, 'Tirol', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (271, 0, 2048, 'Training', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (272, 222, 256, 'Trier', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (273, 0, 2112, 'Turniere', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (274, 40, 256, 'Turnierverwaltungen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (275, 103, 1088, 'Ungarn', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (276, 15, 512, 'Unterfranken', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (277, 295, 384, 'Unterland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (278, 103, 1152, 'USA', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (279, 117, 256, 'Verlage', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (280, 224, 512, 'Vest', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (281, 184, 512, 'Vorarlberg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (282, 160, 192, 'Waldviertel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (283, 208, 64, 'Webforen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (284, 208, 128, 'Weblogs', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (285, 160, 256, 'Weinviertel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (286, 5, 448, 'Weltmeisterschaften', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (287, 161, 320, 'Wesel', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (288, 146, 320, 'West', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (289, 236, 256, 'West', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (290, 255, 192, 'West', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (291, 139, 192, 'West', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (292, 184, 576, 'Wien', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (293, 48, 64, 'Wikis', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (294, 185, 256, 'Wilhelmshaven/Friesland', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (295, 0, 2176, 'Württemberg', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (296, 0, 2240, 'Zeitungen', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (297, 6, 192, 'Zollern/Alb', 1);
INSERT INTO tl_linkscollection (id, pid, sorting, title, published) VALUES (298, 176, 192, 'Zugspitze', 1);
